# Generated by Django 4.2.11 on 2024-05-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('face', models.URLField()),
                ('tel', models.URLField()),
                ('insta', models.URLField()),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='ServiseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'servise',
                'verbose_name_plural': 'servises',
            },
        ),
    ]
